#!/bin/sh
 
appname="quizjs-ms"
 
port=`awk -F= '/^startupPort/ {print $2}' /etc/vdna/$appname/config.properties | tr -d ' '`
if [ ! "$port" ]; then
  echo "Cannot work out port from /etc/vdna/$appname/config.properties" >&2
  exit 1
fi
 
# block the deploy script until quizjs starts
count=0
while ! nc -vz localhost $port > /dev/null 2>&1; do
 sleep 1
 echo -n .
 count=$((count+1))
done
 
echo
echo "Restart took: $count seconds"
