#!/bin/sh

appname="quizjs-ms"

port=`awk -F= '/^startupPort/ {print $2}' /etc/vdna/$appname/config.properties | tr -d ' '`
if [ ! "$port" ]; then
  echo "Cannot work out port from /etc/vdna/$appname/config.properties" >&2
  exit 1
fi

check=$(curl --silent --write-out "%{http_code}" --output /dev/null http://localhost:$port/healthcheck)
if [ "$check" != "200" ]
then
    # "000" status code in curl is intended to indicate that the connection timed out
    echo "Curl call to 'http://localhost:$port/healthcheck' didn't responded with '200'."
    exit 1
fi

echo "All OK!"